name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (если использование Node.js)
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Укажите нужную версию Node.js

    - name: Install dependencies
      run: make setup

    - name: Run tests
      run: make test

    - name: Run linter
      run: make lint
